---
title: "Tables"
output: bookdown::pdf_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(kableExtra)
library(tidyverse)
library(ggplot2)
library(gridExtra)
```

# Top visited private HS (2-mode network)

```{r}
df <- readRDS('./assets/tables/table_2mode.RDS')

knitr::kable(head(df, n = 20)) %>% kable_styling(latex_options = 'scale_down')
```

Table \@ref(tab:hs-print-privu) shows characteristics of the 20 private high schools that were visited by the most private colleges and universities

```{r, hs-print-privu, echo = FALSE}
df <- readRDS('./assets/tables/table_2mode.RDS')

knitr::kable(head(df, n = 20, caption = 'ego table 3')) %>% kable_styling(latex_options = 'scale_down')
```

# Aggregated visited private HS (2-mode network)

```{r}
df <- readRDS('./assets/tables/table_2mode_agg.RDS')

knitr::kable(df) %>% kable_styling(latex_options = 'scale_down')
```

# Ego network table

```{r}
df <- readRDS('./assets/tables/table_ego.RDS')
knitr::kable(df %>% select(-ID, -Characteristics), row.names = F) %>% kable_styling(latex_options = 'scale_down')
```

# Ego network barplot

\newpage

```{r, fig.width=3.5, fig.height=3}
plot_characteristic <- function(df, type, characteristics) {
  sub_df <- df %>% select(University, characteristics) %>%
    gather(key, value, characteristics) %>%
    mutate(value = parse_number(value))

  # colors <- sub_df$color[order(sub_df$University)]
  univ_order <- (df %>% arrange(Cluster, Type, as.numeric(Rank), University))$University  
  sub_df$University <- factor(sub_df$University, levels = rev(univ_order))
  
  ggplot(sub_df, aes(fill = key, y = value, x = University)) + 
    geom_bar(stat='identity', position = position_fill(reverse = TRUE)) +
    ggtitle('Title') +
    xlab('') + ylab('') +
    labs(fill = type) +
    scale_y_continuous(labels = scales::percent, expand = c(0, 0, 0.05, 0)) +
    theme(legend.position = 'top',
          legend.title = element_text(size = 6, face = 'bold'),
          legend.text = element_text(size = 6),
          legend.margin = margin(0, 0, 0, 0),
          legend.box.margin = margin(0, 0, -5, -30),
          legend.key.size = unit(0.3, 'cm'),
          panel.background = element_blank(),
          axis.ticks.y = element_blank(),
          # axis.text.y = element_text(color = rep(c('red', 'green', 'blue', 'yellow', 'black'), 5)),
          text = element_text(size = 8),
          plot.title = element_text(color = 'white')) +
    coord_flip()
}


type_vec <- c('privu', 'pubu')

for (i in 1:length(type_vec)) {
  ego_df <-readRDS(file.path('.', 'assets', 'tables', str_c('table_ego_', type_vec[i], '.RDS')))

  pdf(file.path('.', 'assets', 'figures', str_c('ego_network_figure_', type_vec[i], '.pdf')), paper = 'a4r')
  par(mfrow=c(2, 2))
  
  a <- plot_characteristic(ego_df, 'Region', c('Northeast', 'Midwest', 'South', 'West'))
  b <- plot_characteristic(ego_df, 'Religion', c('Catholic', 'Conserv', 'Nonsect', 'Other'))
  c <- plot_characteristic(ego_df, '% Black/Latinx/Native', c('c1_lt10', 'c2_10to25', 'c3_25to50', 'c4_50+'))
  d <- plot_characteristic(ego_df, 'Ranking', c('c1_top200', 'c2_A+', 'c3_A', 'c4_ltA'))
  
  grid.arrange(a, b, c, d, nrow=2, ncol=2)
  dev.off()
  
  # Need to use print() for ggplot inside loop in order for it to appear
  # https://stackoverflow.com/a/15678596/6373540
  print(a)
  print(b)
  print(c)
  print(d)
}
```


