---
title: "The Private School Network: Recruiting Visits to Private High Schools by Public and Private Universities"
#author: 
#  - Ozan Jaquette
#  - Crystal Han
#  - Irma Castañeda
bibliography: ./../other/burd_recruiting_chapter.bib
output: 
  bookdown::pdf_document2:
    toc: FALSE
    pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
csl: ./../other/apa.csl
urlcolor: blue
header-includes:
      - \usepackage{pdflscape}
      - \usepackage{geometry}
      - \usepackage{floatrow}
      - \usepackage{setspace}
      #- \doublespacing
      - \floatsetup{capposition=top}
fontsize: 12pt
---


```{r setup, include=FALSE}
library(knitr)
library(bookdown)

# https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf
library(kableExtra)
library(tidyverse)
library(gridExtra)
library(scales)

knitr::opts_chunk$set(echo = F, message = F)

knitr::knit_hooks$set(inline = function(x) {   if(!is.numeric(x)){     x   }else{    prettyNum(round(x,2), big.mark=",")    } })

data_dir <- file.path('..', 'data')
tables_dir <- file.path('..', 'assets', 'tables')
figures_dir <- file.path('..', 'assets', 'figures')

univ_sample_df <- readRDS(file.path(data_dir, 'univ_sample.RDS')) %>%
  arrange(desc(classification), rank)
events_df <- readRDS(file.path(data_dir, 'events_data.RDS'))

pubhs_universe_df <- readRDS(file.path(data_dir, 'pubhs_universe.RDS'))
privhs_universe_df <- readRDS(file.path(data_dir, 'privhs_universe.RDS'))

ego_df <- readRDS(file.path(tables_dir, 'table_ego_all.RDS')) %>% 
  mutate(
    univ_region = str_split(characteristics, '\\|', simplify = T)[,1],
    univ_religion = str_split(characteristics, '\\|', simplify = T)[,2],
    univ_race = round(as.numeric(str_split(characteristics, '\\|', simplify = T)[,3]), 1),
    univ_rank = as.numeric(str_split(characteristics, '\\|', simplify = T)[,4]),
    univ_enroll = format(as.numeric(str_split(characteristics, '\\|', simplify = T)[,5]), big.mark = ',')
  )
```

\setstretch{1.5}


ABSTRACT

Few empirical analyses of privatization compare public and private universities on a behavior associated with private universities. This manuscript analyzes off-campus recruiting visits to private high schools, which were made in 2017 by a convenience sample of 15 public research universities and 14 selective, private universities. Sociological scholarship on the relationship between high schools and universities conceives of off-campus recruiting visits as an indicator of a social relation. Therefore, we utilize social network concepts and methods to compare the recruiting networks of public and private universities. With respect to scale (research question 1), most public research universities in our sample made a disproportionate number of visits to private (out-of-state) high schools, though not as many as private universities. With respect to characteristics of visited schools (RQ2), both public and private universities tended to visit predominantly white schools in their home geographic region and the South. Public universities tended to visit lower ranked private high schools than private universities. Surprisingly, several public research universities visited sectarian private high schools at a rate similar to sectarian private universities. With respect to overlap (RQ3), descriptive statistics and community detection methods revealed substantial overlap in the recruiting networks of public and private universities.

\pagenumbering{roman}
\newpage
\pagenumbering{gobble}
\pagenumbering{arabic}

# Introduction

Autumn is college visit season at Harpeth Hall, a non-sectarian private school for girls in Nashville, TN, founded in 1951. According to the 2020 *Best Private High Schools in America* by Niche, Harpeth is an "A+" school ranked 337 in the nation. Enrollment growth at Harpeth and the Nashville-area private school market mirror broader regional patterns, whereby “efforts by the courts to desegregate public schools in the South resulted in White flight to private schools” [@RN4504, p. 14]. In Fall 2017, about 85% of Harpeth students were white and less than 5% were Black or Latinx (Author calculations). 

During the 2017 calendar year, we tracked off-campus recruiting visits made by 14 selective private universities, 12 selective private liberal arts colleges, and 15 public research universities.^[NAME THE UNIVERSITIES]. We are still trying to figure out what happened.

From September 6th through October 17th, Harpeth received recruiting visits from 11 private universities (Northwestern, Boston College, Tufts, Villanova, Case Western Reserve, University of Denvor, Emory, Tulane, Baylor, Texas Christian University), and three private liberal arts colleges from our sample (Harvey Mudd, Scrips, and Sewanee, which visited twice). Harpeth also received visits from the University of Cincinatti, University of South Carolina, the University of Alabama, University of Arkansa, University of Georgia, and CU Boulder.

Four miles northeast of Harpeth, next to Vanderbilt University, is the University School of Nashville. The University School is a nonsectarian, "A+" school, ranked 127th in the nation, and is more racially diverse than Harpeth (64% white, 11.5% Black, 3.5% Latinx, 10.0% Asian). From September 11th 2017 through October 18th, The University School received visits from the same 11 private universities that visited Harpeth (except Notre Dame visited and Baylor did not), five liberal arts colleges (Williams, Middlebury, Sewaneee, Scripps, and Harvey Mudd), but only two public research universities (University of Cincinatti, and CU Boulder). Four miles south of The University School lies Father Ryan High School, a predominantly white (86%, 7% Black or Latinx) Catholic school that received an "A" grade by Niche. In fall 2017, Father Ryan received visits from nine of the 14 private universities in our sample (including all the Catholic universities), just one liberal arts college (Sewanee), and the same six public universities that visited Harpeth Hall, including two visits by the University of Alabama.

Theories of organizational behavior suggest that university recruiting behaviors -- those that require significant expenditure -- are indicators of organizational enrollment priorities. Large, public-facing organizations are beset by multiple, competing pressures from the external environment, but organizations have difficulty pursuing multiple goals [@RN531; @RN959]. Thus, organizations respond by symbolically adopting some goals and substantively adopting others [@RN513]. Under symbolic adoption, organizations adopt policies and structures that send signals to external constituents but do not substantively affect resource allocation inside the the "technical level" of the organization.^[Contingency theory states that organizations consist of "technical levels" responsible for processing inputs and producing outputs and "managerial levels" responsible for directing the technical level and tending to demands from the external environment [@RN531]. The technical level achieves effectiveness by focusing on a small, stable set of goals.] Under substantive adoption, organizations direct resources in the technical level towards achieving the goal. Off-campus recruiting visits to local high schools and college fairs was the top-ranked recruiting expenditure item for both public and private universities, according to @RN4664. Therefore, analyses of which schools a university visits -- and which schools they ignore -- can yield insights about university enrollment goals.

@RN4758 analyzed recruiting visits to public high schools made by 15 public research universities in 2017. the authors found that 12 of the 15 universities made more visits to out-of-state schools than in-state schools. These out-of-state visits focused on affluent, predominantly white public schools. Set against the scholarship about declining state appropriations and growing nonresident enrollment [@RN3753; @RN3685], these results suggest that many public research universities prioritize enrollment from wealthy out-of-state students who can afford to pay nonresident tuition price. 

Within scholarship on social mobility and social stratification, a multidisciplinary literature analyzes the relationship between private school and college [CITE]. This research observes strong links -- and student flows -- between private high schools and selective private universities [CITE]. To date, scholarship on nonresident enrollment by public universities has progressed in isolation from scholarship on links between between private school and college. We argue that these two stories have become connected because public research universities increasingly target out-of-state private schools, schools that have been the domain of selective private universities.

<!-- 
This study compares recruiting visits to private high schools by public research universities and recruiting visits to private high schools by selective private universities. 
We argue that recruiting visits are an indicator of enrollment goals -- the university wants to enroll some students from the school, the school wants some students to enroll at the university. 
-->
This study analyzes recruiting visits to private high schools made in the 2017 calendar year by a sample of 15 public research universities and 14 selective private universities. @RN3519 finds that travel to local high schools is vital for maintaining relationships with guidance counselors at "feeder schools." We conceptualize recruiting visits as an indication the university and the school have a social relationship. This conceptualization motivates the use of social network methods, which analyze networks defined by "network ties" (i.e., visits) between actors (universities and schools). Comparing the recruiting networks of public research universities and selective private universities yields novel insights about competition for students at schools that enroll affluent, "full-pay" students. Analyses are informed by three research questions:

1. How does the scale of visits to private high schools by public research universities compare to the scale of visits to private high schools by selective private universities?
1. How do the characteristics of private high schools visited by public research universities compare to the characteristics of private high schools visited by selective private universities?
1. To what extent do public research universities and selective private universities visit overlapping sets of private high schools?

Both private and public universities in our sample made a disproportionate number of visits to private high schools. For public research universities, visited private schools were much more likely to be out-of-state than visited public schools. Although universities visited a large number of private schools in their home region, most universities also visited a large number of private schools in the South. Private schools that received visits were predominantly white. Although partially a function of our analysis sample, public universities tended to visit lower ranked private high schools than private universities. Surprisingly, several public universities visited sectarian private high schools at a rate similar to sectarian private universities. Network analyses revealed substantial overlap in the recruiting networks of public and private research universities.

This manuscript is practically important because it provides insight about which schools universities view as "feeder schools" and -- to a limited extent -- the characteristics of students they want to enroll. Prior research finds that university recruiting efforts affect the enrollment decisions of students [CITE]. In turn, the composition of enrolled students affects the campus culture experienced by students.  Scholarship and the popular press reports that underrepresented minority students and low-income students at public flagship universities feel isolated amidst affluent, predominantly white student bodies. Racial and socioeconomic isolation negatively affects student development outcomes for isolated students and for the entire student body [CITE]. State policymakers and institutional leaders should recognize that the enrollment composition at public research universities is not the consequence of exogenous student demand, but rather the consequence of recruiting efforts that seek to grow nonresident enrollment by systematically targeting affluent, predominantly white public high schools [@RN4758] and affluent, predominantly white private high schools.
[NOTE: THESE IMPLICATIONS HAVE TO DO ABOUT TARGETING PRIVATE SCHOOLS BUT NOT TARGETING SAME SET OF SCHOOLS TARGETED BY SELECTIVE PRIVATE UNIVERSITIES]



[PUT THIS IN THE DISCUSSION SECTION] Finally When both private and public universities are targeting private schools, competition for these students is likely to increase. This could be an explanation for why many private universities are struggling to meet enrollment goals


student bodies that predonominantly affluent, white student bodies. 

# Literature Review

## Nonresident Enrollment at Public Universities


We stiuate this study vis-a-vis scholarship on enrollment management behavior by public research universities and particularly the pursuit of affluent nonresident students, a population also targeted by selective private universities. The so-called "iron triangle" of enrollment management states that universities pursue the broad enrollment goals of access, academic profile, and revenue generation [@RN3524]. Historically, public research universities prioritize enrollment of high-performing state residents, often with an emphasis on social mobility for students who cannot afford private universities [@RN3608]. By contrast, selective private universities typically prioritize academic profile and revenue generation, with funds generated from tuition and donation feeding the arms race for prestige [@RN3522; @RN1549]. Because resources are scarce, the imagery of the iron triangle suggests that the pursuit of one enrollment goal may involve trade-offs with other goals. @RN2772[p. 221] state that “most enrollment management policies\ldots do not advance all three objectives; instead they lead to gains in some areas and declines in others.” In the 2000s, scholarship on privatization argued the public research universities were emphasizing tuition revenue and rankings and de-emphasizing access for state residents [@RN1577; @RN1118].
<!-- PREVIOUS PARAGRAPH
We situate this study vis-a-vis scholarship on nonresident enrollment at public research universities, which lies within the broader literature on "privatization" [CITE]. Against the backdrop of many states disinvesting in higher education, the privatization literature examines the ways that public universities start behaving like private universities by emphasizing revenue generation and the pursuit of prestige in research and enrollment management behaviors. The so-called "iron triangle" of enrollment management states that universities pursue the three broad enrollment goals of access, academic profile, and revenue generation [CITE]. "Because resources are scarce, the imagery of the iron triangle suggests that the pursuit of one enrollment goal may involve tradeoffs with other goals. Scholarship on privatization expressed concern that the public research universities were emphasizing tuition revenue and rankings and deemphasizing access for state residents.-->


@RN3753 draw from resource dependence theory to conceptualize the relationship between state appropriations and nonresident enrollment. Organizations are dependent on external resources that are important for organizational survival/stability and cannot be easily replaced. Public universities depend on state appropriations but these funds became increasingly uncertain in the 1980s and 1990s [@RN2271]. Resource dependence theory states that one response to resource decline or uncertainty is to seek alternative, substitute resources [CITE]. Tuition revenue is a potential substitute for state appropriations. Most states cap resident tuition price, but not nonresident tuition price. Therefore, @RN3753 argued that public universities have a financial incentive to grow nonresident enrollment in response to declines in state appropriations. Analyzing panel data from 2002-03 to 2012-13, @RN3753 found that a 10% decline in state appropriations was associated with a 2.7% increase in nonresident enrollment at all public universities and a 5.0% increase in nonresident enrollment at research-extensive universities.

Other studies of nonresident enrollment examine university enrollment composition. Using data from NPSAS 2011-12, @RN3685 show that compared to resident students at public research universities, nonresident students generate higher net tuition revenue, are more affluent, are less likely to be Pell recipients and are less likely to be Black or LatinX. Institution-level panel models reveal that growth in the share of nonresident students was associated with a decline in the share of Pell recipients and a decline in the share of Black and LatinX students. @RN4290 examine whether growth in the number of nonresident students causes resident enrollment to decline. They find that nonresident enrollment "crowds out" resident enrollment at prestigious public research universities, but not at less prestigious public research universities.

How did public research universities go about attracting all these nonresident students. One mechanism is financial aid. Many public research universities have developed institutional aid policies for nonresident admits, typically offering larger awards for higher achieving students [@RN3762; @RN2287; @RN1791].<!--@RN2535 shows that nonresident students are less sensitive to sticker price than resident students. Because nonresident prospects may be considering several options -- in-state, out-of-state, public, private -- they are sensitive to the generosity of institutional aid offers [CITE]. For example, @RN3762 analyze the effect of a University of Iowa institutional merit aid program for nonresident admits that offered higher awards for admits with higher academic achievement. Regression discontinuity analyses found that the program increased the probability of enrollment, particularly for high achieving students. These results suggest that high-achieving nonresident students face many good opportunities and require substantial institutional aid to be convinced to enroll. -->

Earlier in the "enrollment funnel," universities utilize marketing and recruiting interventions to attract nonresident applicants. One widely utilized intervention is off-campus recruiting visits by admissions counselors to local high schools. @RN4758 analyzed off-campus recruiting visits to public high schools by 15 public research universities. Recruiting visits to in-state high schools tended exhibit modest racial and socioeconomic bias. However, 12 of the 15 universities made more visits to out-of-state high schools than in-state high schools. These out-of-state visits focused on public schools in affluent, predominantly white communities. @RN4934 conducted geo-spatial analyses of out-of-state recruiting visits to Los Angeles and Dallas by four public research universities. She found that universities engage in "recruitment redlining -- the circuitous avoidance of predominantly Black and Latinx communities along recruiting visit paths" (p. X). Although @RN4758 and @RN4934 focused on visits to public high schools, they noted a surprising number of visits to out-of-state private high schools. 
<!-- However, we know little about this private school visits, for example, which sorts of schools are they visiting and at what scale. -->


## Linkages Between Private Schools and Private Universities



Disconnected from scholarship on nonresident enrollment at public universities, scholarship from economics and sociology analyzes linkages between private schools and colleges.

@RN4504<!-- use data from several national surveys to --> set the stage by analyzing long-term trends in private school enrollment. The percentage of American (elementary school) students attending private school declined from 15% in the mid-1960s to 10% in the mid-1970s, and declined gradually from 11% in 1999 to 9% in 2015. With respect to family income, the private school enrollment rate of high-income families (around 17%) and low-income families (around 4%) remained stable over time, but the enrollment rate for middle-income families declined from 12% in 1968 to 6% in 2013. These declines were substantially driven by declines in the number of students attending Catholic schools, which represented 89% of private school enrollment in 1965 and 42% of enrollment in 2013. However, as Catholic school enrollment has declined, Catholic school students tend to be more affluent than they were in prior decades. In the South, there has been a long-term increase in private school enrollment, driven by growing enrollment in Christian private schools by middle-income families and growing enrollment in nonsectarian private schools by high-income families. With respect to race, in 2013, 11% of white students attended private school compared to 5% of Black students, and 3% of Hispanic students.
<!-- Private school enrollment rates are higher for families located in urban areas than those in suburban areas.
 However, for high income families, rates of private school enrollment do not differ substantially across race. -->

A robust empirical literature<!-- from sociology and economics  --> finds that attending private school positively affects college access and college selectivity [e.g.,] [@RN4642; @RN4596; @RN4634; @RN4599]. Scholarship in the 1990s often focused on the effects of attending Catholic schools [@RN4937; @RN786; @RN4936; @RN4938; @RN4939]. This is because Catholic schools enrolled the majority of private school students and because Catholic school students tended to be less affluent than those at other private schools. <!-- More recent scholarship tends to find that attending a nonsectarian private school has a larger effect on college access outcomes compared to Catholic schools [@RN4614;@RN4625].  --> DESCRIPTIVE STATISTICS FROM HSLS ABOUT PRIVATE SCHOOLS AND SELECTIVE PRIVATE SCHOOLS.

Scholarship has been particularly interested in the relationship between attending an elite private school and attending an elite private college [@RN4647; @RN4643; @RN4647; @RN4589]. @RN4722 acquired unprecedented data -- application files and admissions decisions linked to income tax records  -- to investigate why high income families are over-represented at "Ivy Plus" colleges. Conditioning on SAT and ACT scores, applications from high-income families (top 1%) received the same academic rating as applications from lower-income families. However, applications from high-income families tended to receive higher non-academic ratings (extracurricular activities, leadership traits) then applications from lower-income families. In turn, the higher non-academic ratings for high-income applicants was driven by the fact that these students tended to attend elite private high schools that devote substantial resources to teacher recommendations and guidance counselor letters.

Scholarship from sociology has examined organizational connections that catalyze the flow of students between private schools and selective private colleges [@RN4640; @RN4407; @RN4321; @RN3519]. 

@RN3519 provides an ethnography of the admissions office at a highly selective (but not elite) private liberal arts college. The College is sensitive about its position in U.S. News Rankings and enrollment priorities tend to focus on academic profile and revenue generation. @RN3519 highlights the relational function of off-campus recruiting visits, stating that "the College's reputation and the quality of its applicant pool are dependent upon its connections with high schools nationwide" (p. 54) Therefore, during the autumn "travel season," admissions officers visit selected high schools across the country "to spread word of the institution and maintain relationships with guidance counselors" (p. 53-54). The logic is that a guidance counselor who views a college favorably will steer students to the college. The College tended to visit the same "feeder" schools year after year because recruiting depends on long-term relationships with high schools. The high schools they visited tend to be affluent schools -- in particular, private schools -- that enroll high-achieving students who can afford tuition and have the resources and motivation to host a successful visit. 
<!-- Whereas @RN4402 highlights the effect of recruiting visits on inquiries and enrollees, findings from @RN3519 suggest that the College may have valued recruiting visits primarily as a means of maintaining relationships with guidance counselors. From this perspective, recruiting visits may affect outcomes such as inquiries, applications, and matriculation through their effect on high school guidance counselors. -->

@RN4321 analyzed recruiting from the perspective of an elite private boarding school in order to understand "how such schools continue to get comparatively under-qualified students into top colleges and universities" (p. 98). Guidance counselors at elite private schools capitalize on the fact that college admissions offices value credible information about which applicants will accept or decline an admissions offer because colleges are sensitive to their acceptance and yield rates. This desire for credible intelligence creates an opportunity for high school counselors to advocate on behalf of their students. This opportunity depends on guidance counselors having personal relationships with university admissions offices and on having small enough caseloads to advocate for each student individually. Guidance counselors tell admissions counselors which highly-sought-after applicants are likely to decline an offer, while lobbying for an applicant who relatively weak academic credentials, but has "character," and extracurricular activities the college needs, and who is sure to matriculate.

## Synthesis

Our review of two literatures -- scholarship on nonresident enrollment by public research universities and scholarship on linkages between private schools and private colleges -- suggests an opportunity to bridge and contribute to both literatures.

Historically, public universities received most of their revenue from state funding and enrollment goals prioritized opportunities for in-state students. As state funding became uncertain, public research universities began to prioritize tuition revenue and sought affluent, out-of-state students who paid high nonresident tuition price. Salazar et al shows that recruiting visits by public research universities out-of-state public schools in affluent, predominantly white communities. Resource dependence theory suggests that as public research universities become more tuition reliant, they will start behaving more like selective private universities in targeting private schools which tend to enroll affluent students that can to pay high tuition prices. However, prior research has not investigated visits to private schools. For example, which sorts of private schools are public research universities visiting and at what scale?

The majority of scholarship on linkages between private high schools and private universities focuses on elite high schools and elite universities [CITE]. We know much less about linkages between private schools and private universities that are selective but not elite. These universities are sensitive about their reputation. Despite being relatively affluent, they are much more resource constrained than Ivy Plus. Thus, they cannot pursue all enrollment goals with equal vigor. Prior research shows that selective but not elite colleges prioritize academic profile (as defined by US News Rankings) and tuition revenue, potentially at the expense of access. Many private high schools enroll students that satisfy both enrollment goals. However, prior scholarship provides little insight about which private schools have relationships with selective private universities.

We argue that a recruiting visit from a university to a private high school is an indicator of a relationship. Empirically, @RN3519 finds that off-campus recruiting visits are important for the maintenance of strong relationships between a college and a high school. Logically, the fact that the college made the effort to visit suggests that the college wants to enroll students from the high school. Similarly, the fact that the high school hosted the visit suggests that the high school likely views the college as a desirable destination for some of its students. Moreover, the presence of the recruiting visit suggests the probability of additional interactions (e.g., phone calls) between the organizations. Conceptualizing a recruiting visit as an indicator of a relationship between a college and a high school motivates the use of social network methods, which analyze the network defined by "network ties" (i.e., visits) between actors (universities and schools).

Because nonresident enrollment is a relatively new phenomenon for most public research universities [CITE], visits to out-of-state private schools are encroachments on territory that was previously the domain of selective private universities and in-state public flagships. These visits suggest that public research universities are competing with selective private universities for private school students. This may be direct competition for the same student or vying to be the second choice for students who are rejected by their top choice. By analyzing the network of recruiting visits, we can determine the extent to which public research universities are visiting the same or similar sets of private high schools. These analyses provide a novel lens into the nature of competition between public research universities and selective private universities. They also yield insight about which student bodies these universities want to enroll.
